# PSDK-Linux for EdgeAI: 10.01.00.02

# Below are for osrt-libs-build. References:
# https://git.ti.com/cgit/edgeai/meta-edgeai/tree/recipes-tisdk/ti-tidl/ti-tidl.bb?h=scarthgap
# https://git.ti.com/cgit/edgeai/meta-edgeai/tree/recipes-tisdk/ti-tidl/ti-tidl-osrt.bb?h=scarthgap
arm-tidl:
  url: "https://git.ti.com/git/processor-sdk-vision/arm-tidl.git"
  tag: "REL.PSDK.ANALYTICS.10.01.00.02"
  branch: "master"
  commit: "d165b9ba24c28d23c28bc2f3eed15edc2569ee76"

concerto:
  url: "https://git.ti.com/git/processor-sdk/concerto.git"
  tag: "REL.PSDK.ANALYTICS.10.01.00.02"
  branch: "main"
  commit: "707b11afdbe5d0abb109a42b06828ba70f555bff"

# protobuf_ver_rel is typically the last two release numbers of protobuf_ver.
onnxruntime:
  url: "https://github.com/TexasInstruments/onnxruntime.git"
  tag: "None"
  branch: "tidl-1.15"
  commit: "f145bec7bee26b9dfa43b3e07645ee1a5f8b8140"
  onnx_ver: "1.15.0"
  tidl_ver: "10000005"
  protobuf_ver: "3.21.12"
  protobuf_ver_rel: "21.12"

tensorflow:
  url: "https://github.com/TexasInstruments/tensorflow.git"
  tag: "REL.TIDL.10.00.00.03"
  branch: "tidl-j7-2.12"
  commit: "422156a973b23bab6b86176a245a66193dccb995"
  tf_ver: "2.12"

neo-ai-dlr:
  url: "https://github.com/TexasInstruments/neo-ai-dlr.git"
  tag: "TIDL_PSDK_10.0.2"
  branch: "tidl-j7"
  commit: "2c932cf08f81f69a205e415b2cf3227107fb7ecb"
  dlr_ver: "1.13.0"

ti-rpmsg-char:
  url: "https://git.ti.com/git/rpmsg/ti-rpmsg-char.git"
  tag: "0.6.7"
  branch: "master"
  commit: "5100a2e4a4a951e40ea0708fa78960770ec0ac33"

vision-apps-lib-build:
  url: "https://github.com/TexasInstruments-Sandbox/edgeai-vision-apps-lib-build/releases/download"
  release: "10.01.00.02"
  sdk_ver: "10.1.0"
