name: master-workflow-debian top

on:
  workflow_dispatch:

jobs:
  ## Docker build
  docker_build_debian12-5:
    uses: ./.github/workflows/docker-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "debian:12.5"
      sdk_ver: 10.1.0

  ## Library build: Debian 12.5
  onnxrt_build_debian12-5:
    needs: docker_build_debian12-5
    uses: ./.github/workflows/lib-onnxrt-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "debian:12.5"
      sdk_ver: 10.1.0

  tflite_build_debian12-5:
    needs: docker_build_debian12-5
    uses: ./.github/workflows/lib-tflite-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "debian:12.5"
      sdk_ver: 10.1.0

  dlr_build_debian12-5:
    needs: docker_build_debian12-5
    uses: ./.github/workflows/lib-dlr-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "debian:12.5"
      sdk_ver: 10.1.0

  tidl_build_debian12-5:
    needs: docker_build_debian12-5
    uses: ./.github/workflows/lib-tidl-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "debian:12.5"
      sdk_ver: 10.1.0

  ## Release
  release_debian12-5:
    uses: ./.github/workflows/release-debian.yaml
    needs:
      - onnxrt_build_debian12-5
      - tflite_build_debian12-5
      - dlr_build_debian12-5
      - tidl_build_debian12-5
    secrets:
      gh_TOKEN: ${{ secrets.GHCR_PAT }}
    with:
      sdk_ver: 10.1.0
