name: master-workflow-ubuntu top

on:
  workflow_dispatch:

jobs:
  ## Docker build
  docker_build_ubuntu22-04:
    uses: ./.github/workflows/docker-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "ubuntu:22.04"
      sdk_ver: 10.0.0

  ## Library build: Ubuntu 22.04
  onnxrt_build_ubuntu22-04:
    needs: docker_build_ubuntu22-04
    uses: ./.github/workflows/lib-onnxrt-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "ubuntu:22.04"
      sdk_ver: 10.0.0

  tflite_build_ubuntu22-04:
    needs: docker_build_ubuntu22-04
    uses: ./.github/workflows/lib-tflite-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "ubuntu:22.04"
      sdk_ver: 10.0.0

  dlr_build_ubuntu22-04:
    needs: docker_build_ubuntu22-04
    uses: ./.github/workflows/lib-dlr-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "ubuntu:22.04"
      sdk_ver: 10.0.0

  tidl_build_ubuntu22-04:
    needs: docker_build_ubuntu22-04
    uses: ./.github/workflows/lib-tidl-build.yaml
    secrets:
      env_PAT: ${{ secrets.GHCR_PAT }}
    with:
      arch: arm64
      base_image: "ubuntu:22.04"
      sdk_ver: 10.0.0

  ## Release
  release_ubuntu22-04:
    uses: ./.github/workflows/release-ubuntu.yaml
    needs:
      - onnxrt_build_ubuntu22-04
      - tflite_build_ubuntu22-04
      - dlr_build_ubuntu22-04
      - tidl_build_ubuntu22-04
    secrets:
      gh_TOKEN: ${{ secrets.GHCR_PAT }}
    with:
      sdk_ver: 10.0.0
